name = "SCOL"
uuid = "53762b12-3835-473d-a1b4-0719f1844279"
authors = ["Gergo Fodor"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
